# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from test_controller.swagger_server.models.base_model_ import Model
from test_controller.swagger_server import util


class Test(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, test_id: int=None, name: str=None, prams: str=None):  # noqa: E501
        """Test - a model defined in Swagger

        :param test_id: The test_id of this Test.  # noqa: E501
        :type test_id: int
        :param name: The name of this Test.  # noqa: E501
        :type name: str
        :param prams: The prams of this Test.  # noqa: E501
        :type prams: str
        """
        self.swagger_types = {
            'test_id': int,
            'name': str,
            'prams': str
        }

        self.attribute_map = {
            'test_id': 'testId',
            'name': 'name',
            'prams': 'prams'
        }
        self._test_id = test_id
        self._name = name
        self._prams = prams

    @classmethod
    def from_dict(cls, dikt) -> 'Test':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Test of this Test.  # noqa: E501
        :rtype: Test
        """
        return util.deserialize_model(dikt, cls)

    @property
    def test_id(self) -> int:
        """Gets the test_id of this Test.


        :return: The test_id of this Test.
        :rtype: int
        """
        return self._test_id

    @test_id.setter
    def test_id(self, test_id: int):
        """Sets the test_id of this Test.


        :param test_id: The test_id of this Test.
        :type test_id: int
        """

        self._test_id = test_id

    @property
    def name(self) -> str:
        """Gets the name of this Test.


        :return: The name of this Test.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Test.


        :param name: The name of this Test.
        :type name: str
        """

        self._name = name

    @property
    def prams(self) -> str:
        """Gets the prams of this Test.


        :return: The prams of this Test.
        :rtype: str
        """
        return self._prams

    @prams.setter
    def prams(self, prams: str):
        """Sets the prams of this Test.


        :param prams: The prams of this Test.
        :type prams: str
        """

        self._prams = prams
